CREATE TABLE IF NOT EXISTS "user" (
	"id" VARCHAR(255) NOT NULL,
	"wx_openid" VARCHAR(255),
	"phone" VARCHAR(255),
	"wx_name" VARCHAR(255),
	"role_type" INTEGER,
	PRIMARY KEY("id")
);


CREATE INDEX "user_index_0"
ON "user" ("id");

CREATE TABLE IF NOT EXISTS "message" (
	"id" VARCHAR(255) NOT NULL UNIQUE,
	"user_id" VARCHAR(255),
	-- 表单内容
	"content" TEXT,
	"delete" BOOLEAN,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "message"."content" IS '表单内容';


CREATE TABLE IF NOT EXISTS "pic" (
	-- 用户图片
	"id" VARCHAR(255) NOT NULL,
	"uesr_id" VARCHAR(255),
	"picUrl" VARCHAR(255),
	-- 父节点-如果设计编辑后，可以参考反馈查看
	"pid" VARCHAR(255),
	-- 备注
	"remake" TEXT,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "pic"."id" IS '用户图片';
COMMENT ON COLUMN "pic"."pid" IS '父节点-如果设计编辑后，可以参考反馈查看';
COMMENT ON COLUMN "pic"."remake" IS '备注';
CREATE INDEX "pic_index_0"
ON "pic" ("id");

CREATE TABLE IF NOT EXISTS "voice" (
	"id" VARCHAR(255) NOT NULL,
	"user_id" VARCHAR(255),
	-- 音频文件地址
	"url" VARCHAR(255),
	-- 音频备注
	"remark" VARCHAR(255),
	-- 音频文字转换结果
	"content" TEXT,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "voice"."url" IS '音频文件地址';
COMMENT ON COLUMN "voice"."remark" IS '音频备注';
COMMENT ON COLUMN "voice"."content" IS '音频文字转换结果';


CREATE TABLE IF NOT EXISTS "trash" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	-- 源id
	"source_id" VARCHAR(255),
	-- 垃圾源类型
	"type" INTEGER,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "trash"."source_id" IS '源id';
COMMENT ON COLUMN "trash"."type" IS '垃圾源类型';


CREATE TABLE IF NOT EXISTS "auth" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- 会员名称
	"name" VARCHAR(255),
	-- 音频转文字权限
	"voice_message" BOOLEAN,
	-- 垃圾箱最多保留时间非会员7天,会员30天
	"trash" INTEGER,
	PRIMARY KEY("id")
);

COMMENT ON TABLE "auth" IS '权限-用户权限';
COMMENT ON COLUMN "auth"."name" IS '会员名称';
COMMENT ON COLUMN "auth"."voice_message" IS '音频转文字权限';
COMMENT ON COLUMN "auth"."trash" IS '垃圾箱最多保留时间非会员7天,会员30天';

ALTER TABLE "user"
ADD FOREIGN KEY("role_type") REFERENCES "auth"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "message"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "pic"("uesr_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "user"
ADD FOREIGN KEY("id") REFERENCES "voice"("user_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "message"
ADD FOREIGN KEY("id") REFERENCES "trash"("source_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "pic"
ADD FOREIGN KEY("id") REFERENCES "trash"("source_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "voice"
ADD FOREIGN KEY("id") REFERENCES "trash"("source_id")
ON UPDATE NO ACTION ON DELETE NO ACTION;