// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"quick_meesage/backend/internal/config"
	"quick_meesage/backend/internal/repository"
	"quick_meesage/backend/internal/service"
	"quick_meesage/backend/internal/storage"
	"quick_meesage/backend/internal/transport/grpc"
	"quick_meesage/backend/internal/transport/http"
)

// Injectors from wire.go:

func Initialize() (*App, func(), error) {
	configConfig := config.New()
	client, cleanup, err := storage.NewEntClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	ideaRepository := repository.NewIdeaRepository(client)
	ideaService := service.NewIdeaService(ideaRepository)
	server := httpserver.New(configConfig, ideaService)
	grpcServer := grpcserver.New(ideaService)
	app := New(configConfig, client, server, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
