// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"quick_meesage/backend/internal/config"
	"quick_meesage/backend/internal/storage"
	grpcserver "quick_meesage/backend/internal/transport/grpc"
	httpserver "quick_meesage/backend/internal/transport/http"
)

// Injectors from wire.go:

func Initialize() (*App, func(), error) {
	configConfig := config.New()
	client, cleanup, err := storage.NewEntClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	db, cleanup2, err := storage.NewDB(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	server := httpserver.New(configConfig)
	grpcServer := grpcserver.New()
	app := New(configConfig, client, db, server, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
