// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"quick_message/backend/internal/conf"
	"quick_message/backend/internal/data"
	"quick_message/backend/internal/data/repoiface"
	"quick_message/backend/internal/handler"
	"quick_message/backend/internal/server"
	"quick_message/backend/internal/service/wechat"
)

// Injectors from wire.go:

func initDataClient(conf2 *conf.Config) (*data.Client, func(), error) {
	db, err := data.NewSQLDB(conf2)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewEntClient(db)
	if err != nil {
		return nil, nil, err
	}
	dbProvider := data.NewDBProvider(client)
	node, err := data.NewSnowflakeNode()
	if err != nil {
		return nil, nil, err
	}
	idGenerator := data.NewIDGenerator(node)
	redisClient, err := data.NewRedisClient(conf2)
	if err != nil {
		return nil, nil, err
	}
	sequencer := data.NewSequencer(redisClient)
	locker := data.NewLocker(redisClient)
	cache := data.NewCache(redisClient)
	queryHelper := data.NewQueryHelper()
	base := repoiface.NewBase(dbProvider, idGenerator, sequencer, locker, cache, queryHelper)
	dataClient := &data.Client{
		Base: base,
	}
	return dataClient, func() {
	}, nil
}

func initApiApp(conf2 *conf.Config, dbClient *data.Client) (*server.ApiServer, func(), error) {
	healthHandler := handler.NewHealthHandler()
	service := wechatsvc.NewService(conf2)
	wechatHandler := handler.NewWechatHandler(service)
	apiServer, cleanup, err := server.NewHandlerServer(conf2, dbClient, healthHandler, wechatHandler)
	if err != nil {
		return nil, nil, err
	}
	return apiServer, func() {
		cleanup()
	}, nil
}
