// Code generated by hand for the bootstrap. Equivalent to what
// `wire ./cmd/server` would produce. Safe to overwrite by running wire later.
//
// 注:此文件没有 //go:build wireinject 标签,所以普通 go build 会编译它,
// 而 wire.go 仅在 wire 工具运行时才被编译。

package main

import (
	"quick_message/backend/internal/data"
	"quick_message/backend/internal/handler"
	"quick_message/backend/internal/conf"
	"quick_message/backend/internal/server"
)

func initDataClient(c *conf.Config) (*data.Client, func(), error) {
	client, cleanup, err := data.NewClient(c)
	if err != nil {
		return nil, nil, err
	}
	return client, cleanup, nil
}

func initApiApp(c *conf.Config, db *data.Client) (*server.ApiServer, func(), error) {
	h := handler.NewHealthHandler()
	srv, cleanup, err := server.NewApiServer(c, db, h)
	if err != nil {
		return nil, nil, err
	}
	return srv, cleanup, nil
}
