package schema

import (
	"database/sql"
	"fmt"
)

const createAuthTable = `
CREATE TABLE IF NOT EXISTS "auth" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255),
	"voice_message" BOOLEAN,
	"trash" INTEGER,
	PRIMARY KEY("id")
);
COMMENT ON TABLE "auth" IS '权限-用户权限';
COMMENT ON COLUMN "auth"."name" IS '会员名称';
COMMENT ON COLUMN "auth"."voice_message" IS '音频转文字权限';
COMMENT ON COLUMN "auth"."trash" IS '垃圾箱最多保留时间非会员7天,会员30天';
`

// Auth 定义权限表结构
type Auth struct {
	ID int64  // 权限ID
	Name         string // 会员名称
	VoiceMessage bool   // 音频转文字权限
	Trash        int    // 垃圾箱保留天数
}

// MigrateAuth 创建权限表
func MigrateAuth(db *sql.DB) error {
	_, err := db.Exec(createAuthTable)
	return err
}

// ScanAuth 从数据库行扫描 Auth
func ScanAuth(row interface {
	Scan(...interface{}) error
}) (*Auth, error) {
	var a Auth
	var name, voiceMessage, trash sql.NullString
	err := row.Scan(&a.ID, &name, &voiceMessage, &trash)
	if err != nil {
		return nil, fmt.Errorf("scan auth: %w", err)
	}
	a.Name = name.String
	a.VoiceMessage = voiceMessage.String == "true"
	if trash.String != "" {
		fmt.Sscanf(trash.String, "%d", &a.Trash)
	}
	return &a, nil
}