package schema

import (
	"database/sql"
	"fmt"
)

const createTrashTable = `
CREATE TABLE IF NOT EXISTS "trash" (
	"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"source_id" VARCHAR(255),
	"type" INTEGER,
	PRIMARY KEY("id")
);
`

// TrashType 定义垃圾类型枚举
type TrashType int

const (
	TrashTypeMessage TrashType = iota + 1
	TrashTypePic
	TrashTypeVoice
)

// Trash 定义垃圾回收表结构
type Trash struct {
	ID int64     // 垃圾记录ID
	SourceID string // 源ID
	Type     TrashType // 垃圾源类型
}

// MigrateTrash 创建垃圾回收表
func MigrateTrash(db *sql.DB) error {
	_, err := db.Exec(createTrashTable)
	return err
}

// ScanTrash 从数据库行扫描 Trash
func ScanTrash(row interface {
	Scan(...interface{}) error
}) (*Trash, error) {
	var t Trash
	var typeInt int
	err := row.Scan(&t.ID, &t.SourceID, &typeInt)
	if err != nil {
		return nil, fmt.Errorf("scan trash: %w", err)
	}
	t.Type = TrashType(typeInt)
	return &t, nil
}